const Path = {
    HOME: '/',
    LOGIN: '/login',
    LOGOUT: '/logout',
    LOGS: 'logs/list',
    REGISTER: '/register',
    EDIT_PROFILE: '/edit_profile',
    USERS: 'dashboard/users_list',
    DELETE_USER: 'dashboard/delete_user',
    ARTICLES: '/articles',
    EDIT_ARTICLE: '/edit_article',
    ADD_ARTICLE: '/add_article',
    IMAGES_PREVIEW: '/images_preview',
    DASHBOARD: '/dashboard',
    Error404: '/error404',
    ATTACH_RESPONSIBILITIES: '/users/responsibilities/attach',
    DETACH_RESPONSIBILITIES: '/users/responsibilities/detach',
    CREATE_STORE: '/stores/create',
    EDIT_STORE: '/stores/edit',
    DELETE_STORE: '/stores/delete',
    STORES: 'stores/list',
    // STORE: '/store',
}

export default Path;